pub mod adopt;
pub mod agents;
pub mod brief;
pub mod claim;
pub mod close;
pub mod config_cmd;
pub mod context;
pub mod create;
pub mod delete;
pub mod dep;
pub mod diff;
pub mod doctor;
pub mod edit;
pub mod fact;
pub mod graph;
pub mod groom;
pub mod init;
pub mod interactive;
pub mod list;
pub mod locks;
pub mod logs;
pub mod mcp;
pub mod memory_context;
pub mod move_units;
pub mod mutate;
pub mod next;
pub mod onboard;
pub mod plan;
pub mod quick;

pub mod recall;
pub mod reopen;
pub mod review;
pub mod run;
pub mod search;
pub mod show;
pub mod stats;
pub mod status;
pub mod stdin;
pub mod sync;
pub mod tidy;
pub mod trace;
pub mod tree;
pub mod trust;
pub mod unarchive;
pub mod update;
pub mod verify;

pub use adopt::cmd_adopt;
pub use agents::cmd_agents;
pub use brief::cmd_brief;
pub use claim::{cmd_claim, cmd_release};
pub use close::{cmd_close, cmd_close_failed};
pub use config_cmd::{cmd_config_get, cmd_config_set};
pub use context::cmd_context;
pub use create::{cmd_create, cmd_create_next};
pub use delete::cmd_delete;
pub use dep::{cmd_dep_add, cmd_dep_list, cmd_dep_remove};
pub use diff::cmd_diff;
pub use doctor::cmd_doctor;
pub use edit::{cmd_edit, load_backup, open_editor};
pub use fact::{cmd_fact, cmd_verify_facts};
pub use graph::cmd_graph;
pub use groom::cmd_groom;
pub use init::{cmd_init, InitArgs};
pub use list::cmd_list;
pub use locks::{cmd_locks, cmd_locks_clear};
pub use logs::cmd_logs;
pub use mcp::cmd_mcp_serve;
pub use memory_context::cmd_memory_context;
pub use move_units::{cmd_move_from, cmd_move_to};
pub use mutate::cmd_mutate;
pub use next::cmd_next;
pub use onboard::cmd_onboard;
pub use plan::cmd_plan;
pub use quick::cmd_quick;

pub use recall::cmd_recall;
pub use reopen::cmd_reopen;
pub use review::{cmd_review, ReviewArgs};
pub use run::cmd_run;
pub use search::cmd_search;
pub use show::cmd_show;
pub use stats::cmd_stats;
pub use status::cmd_status;
pub use sync::cmd_sync;
pub use tidy::cmd_tidy;
pub use trace::cmd_trace;
pub use tree::cmd_tree;
pub use trust::cmd_trust;
pub use unarchive::cmd_unarchive;
pub use update::cmd_update;
pub use verify::cmd_verify;
